version: "3.9"
services:

  kcu:
    build: .
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres