version: "3.9"
services:

  kcu:
    build: .
    restart: 'no'
    environment:
      SQL_PASSWORD: postgres
      SQL_USER: postgres
      SQL_DB: postgres
      SQL_HOST: postgres
      SQL_PORT: "5432"
    depends_on:
      - postgres
    command: sh /srv/KaggleChallenge/run_pytest.sh

  mlflow:
    image: ghcr.io/mlflow/mlflow
    restart: always
    command: tail -F anything

  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
